=== bodand/Nought/src/main/resources/nought.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" targetNamespace="https://kszi2.hu/~bodand/nought.xsd"
					 xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ngt="https://kszi2.hu/~bodand/nought.xsd" version="1.1">
	<xs:element name="nought">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="ngt:todosType" name="todos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="todosType">
		<xs:sequence>
			<xs:element name="todo" type="ngt:todoType" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="todoType">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="desc" type="xs:string" />
			<xs:element name="completed" type="ngt:completedType" minOccurs="0" />
			<xs:element name="depends-on" type="ngt:dependsOnType" minOccurs="0" />
			<xs:element name="due" type="ngt:dueType" minOccurs="0" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required" />
	</xs:complexType>

	<xs:complexType name="dependsOnType">
		<xs:sequence>
			<xs:element name="todo" type="ngt:todorefType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="todorefType">
		<xs:attribute name="ref" type="xs:IDREF" use="required" />
	</xs:complexType>

	<xs:complexType name="dueType">
		<xs:sequence>
			<xs:element name="date" type="xs:date" />
			<xs:element name="time" type="xs:time" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="completedType" />
</xs:schema>

=== bodand/Nought/src/main/resources/test.xml
<?xml version="1.0" encoding="UTF-8" ?>
<nought xmlns="https://kszi2.hu/~bodand/nought.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				xsi:schemaLocation="https://kszi2.hu/~bodand/nought.xsd file://nought.xsd">
	<todos>
		<todo id="_60f2abf2-f76d-49f9-a4a5-c87b13a9cbbc">
			<name>Todo 1</name>
			<desc>Todo text</desc>
		</todo>
		<todo id="_c2a32159-662f-42c9-a1a3-740ebe15cb00">
			<name>Todo 2</name>
			<desc>Todo text 2</desc>
			<depends-on>
				<todo ref="_60f2abf2-f76d-49f9-a4a5-c87b13a9cbbc" />
			</depends-on>
			<due>
				<date>2022-11-07</date>
				<time>23:59:00</time>
			</due>
		</todo>
	</todos>
</nought>
